pipeline {
    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        REPO_URL = "https://github.com/Brathaban/Jenkins-Zero-To-Hero.git"
        MANIFEST_PATH = "python-jenkins-argocd-k8s/ArgocdViewing/deploy.yaml"
    }

    stages {

        stage('Checkout Source') {
            steps {
                git url: "${REPO_URL}", branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                echo 'Building Docker Image'
                docker build -t abhishekf5/cicd-e2e:${IMAGE_TAG} .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                echo 'Pushing Docker Image'
                docker push abhishekf5/cicd-e2e:${IMAGE_TAG}
                '''
            }
        }

        stage('Update K8s Manifest') {
            steps {
                sh '''
                echo 'Updating deploy.yaml with new image tag'
                cd python-jenkins-argocd-k8s/ArgocdViewing
                sed -i "s|abhishekf5/cicd-e2e:.*|abhishekf5/cicd-e2e:${IMAGE_TAG}|g" deploy.yaml
                cat deploy.yaml
                '''
            }
        }

        stage('Commit & Push Changes') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.name "Jenkins Bot"
                    git config user.email "jenkins@local"
                    git add ${MANIFEST_PATH}
                    git commit -m "Update image tag to ${IMAGE_TAG} | Jenkins Pipeline"
                    git remote set-url origin https://${GITHUB_TOKEN}@github.com/Brathaban/Jenkins-Zero-To-Hero.git
                    git push origin HEAD:main
                    '''
                }
            }
        }
    }
}
